### ISSUE TITLE
How to get angular velocity from MPU 6050 in Arduino.

### ISSUE THREAD

**Issue by anishk25** [jrowberg/i2cdevlib#132]
Hi,

I am trying to get the yaw angular velocity from the MPU 6050 gyroscope. I followed the example sketch to obtain the yaw of the gyroscope but how can I get the angular velocity as well. Is there any better way other than using the millis() function in Arduino to accomplish this?

**Comment by mariocannistra** [comment]
Hi anishk25.
You can find the answer here:  http://www.i2cdevlib.com/forums/topic/106-get-angular-velocity-from-mpu-6050/

The raw output of the gyroscope is the angular velocity expressed in degrees/second.
I suggest you download the datasheet where you can get all the details about precision / scales / errors etc :  http://www.invensense.com/mems/gyro/documents/PS-MPU-6000A-00v3.4.pdf
Mario
