### ISSUE TITLE
DMP API

### ISSUE THREAD

**Issue by Marsfan** [jrowberg/i2cdevlib#138]
Hi,
I am trying to get the MPU6050 working on the raspberry pi using python. Is there a document that states what registers to send the DMP code, what that code is, and how to then read the data?
I am new at programming, so I would like to try to write this myself, instead of just downloading code that I do not understand.

**Comment by jrowberg** [comment]
Closing ancient issue for cleanup. In short, there is no DMP documentation other than the various C++ implementations and I2C logic analyzer captures. Possibly some helpful info in the official embedded MotionApps code from TDK/InvenSense.
