### ISSUE TITLE
I2Cdev uinitialized 'b' on raspberry pi

### ISSUE THREAD

**Issue by sgsdxzy** [jrowberg/i2cdevlib#187]
on pi's I2Cdev.cpp line 89:

    int8_t b;

should be
 
    int8_t b = (uint8_t) recvBuf[0];

That's why testConnection() methods almost always fails on raspberry pi: readBits is returning random results.

**Comment by jrowberg** [comment]
You're correct. I'm not sure how that one slipped through, but it's fixed now.
