### ISSUE TITLE
Do I need use a Kalman Filter or others using a DMP mode?

### ISSUE THREAD

**Issue by opvini** [jrowberg/i2cdevlib#200]
Hi everyone,
when I use a DMP mode, I saw the values are filtered. So, I don't need to use others filters (Kalman or Complementary) after read data from DMP mode?

Thanks a lot

**Comment by hgvk94** [comment]
Hi
You need not implement any fusion algorithms in your code.The DMP does this for you. the guys who manufacture these(http://www.invensense.com/products/motion-tracking/6-axis/mpu-6050/ ) havent revealed what algorithm they have used inside the DMP to accomplish this, but it does provide pretty stable results. 
See this link for a comparison in performance: http://www.geekmomprojects.com/mpu-6050-redux-dmp-data-fusion-vs-complementary-filter/

Cheers

**Comment by opvini** [comment]
Very good!
Thanks a lot @hgvk94
