### ISSUE TITLE
’class TwoWire’ has no member named ‘setClock

### ISSUE THREAD

**Issue by jorgediosdado** [jrowberg/i2cdevlib#237]
Hi,

I am trying to use MPU6050 library, but i am getting this compilation error: 

MPU6050_DMP6.ino: In function ‘void setup()’:
MPU6050_DMP6.ino:166:14: error: ‘class TwoWire’ has no member named ‘setClock’
MPU6050_DMP6.ino:216:60: error: ‘digitalPinToInterrupt’ was not declared in this scope

Any idea on what the issue may be? 

Cheers!

**Comment by eadf** [comment]
Both of those methods are relatively new, what version of Arduino are you using?

**Comment by jorgediosdado** [comment]
I was using Arduino 1.0.5
I uploaded to the newest version and I don't get that error anymore, so problem solved. Thanks @eadf

**Comment by eadf** [comment]
You're welcome
