### ISSUE TITLE
MPU6050 data delay

### ISSUE THREAD

**Issue by EmbeddedFiedel** [jrowberg/i2cdevlib#24]
Hello everyone, I have a problem with the mpu6050. All works quite well, but when I am not able to handle a data ready interrupt of the mpu6050 the fifo is growing and i am getting a delay on the data.

To solve this issue i tried to implement a loop that reads fifo packets until the fifocount is smaller than the packetsize. But when i do this i get crazy peaks on my signal (every third value). Do you have a solution for this?

![mpu6050_problem](https://f.cloud.github.com/assets/1910575/162453/e9a6a734-77ba-11e2-8f7a-3e75320896e8.png)

**Comment by Siddharth1996** [comment]
Thanks a lot jrowberg :D
