### ISSUE TITLE
I2Cdev.cpp with small BUFFER_LENGTH

### ISSUE THREAD

**Issue by cschou100** [jrowberg/i2cdevlib#243]
Hi,
Currently, I use a device support only very small buffer length and get fail result.
In the following code (readBytes), do you think that line 278 should be changed to 
Wire.write(regAddr+k) ?

Thanks

276            for (uint8_t k = 0; k < length; k += min(length, BUFFER_LENGTH)) { 
277                 Wire.beginTransmission(devAddr); 
278                 Wire.write(regAddr); 
279                 Wire.endTransmission(); 
280                 Wire.beginTransmission(devAddr); 
281                 Wire.requestFrom(devAddr, (uint8_t)min(length - k, BUFFER_LENGTH)); 
282  
283                 for (; Wire.available() && (timeout == 0 || millis() - t1 < timeout); count++) { 
284                     data[count] = Wire.read(); 
285                     #ifdef I2CDEV_SERIAL_DEBUG 
286                         Serial.print(data[count], HEX); 
287                         if (count + 1 < length) Serial.print(" "); 
288                     #endif 
289                 }

**Comment by jrowberg** [comment]
Errors related to `BUFFER_LENGTH` should now been resolved. However, if you have an MCU with an extremely small quantity of RAM, you should be able to decrease the buffer length slightly (see `I2Cdev.h` near the top). Transactions will be less efficient if they are always broken up into chunks, but the RAM requirement may drop slightly.
