### ISSUE TITLE
RA, TC ... What do they stand for?

### ISSUE THREAD

**Issue by streamnsight** [jrowberg/i2cdevlib#266]
What do RA, and TC prefix stand for? 
I couldn't figure this from the docs.

Thanks.

**Comment by jrowberg** [comment]
The "RA" segment of a constant typically means **register address**, while everything after that comes from the register map or datasheet and is defined by the manufacturer. In the case of "MPU6050_RA_XG_OFFS_TC" and similar, I believe "TC" stands for test constant or test calibration or something similar. The register map is not clear about those registers and what they do.

**Comment by streamnsight** [comment]
Thanks! 
it makes more sense now.

**Comment by streamnsight** [comment]
by the way, are you familiar with the fact that InvenSense published the actual code for the MPU6050 DMP functions?

This includes quite a few interesting features such as tap detection, fall detection, no motion detection, heading, orientation detection etc...


the latest can be download in their Developper section (registration required) under Motion Driver 6.2



________________________________
