### ISSUE TITLE
Correct Gyro conversion?

### ISSUE THREAD

**Issue by thomasck** [jrowberg/i2cdevlib#286]
I am trying to figure out the correct gyro conversion to get the values from dmpGetGyro(int16_t *data, const uint8_t* packet) into radians per second. 

Using the default setting of 2000 dps the correct conversion should be (2000/32768)*(pi/180), but multiplying this by the dmp gyro values yields results that are much too small to be correct. For example I have tested this by rotating the chip pi/2 radians in roughly 1 second yet got results far lower than pi/2 rad/s

I would greatly appreciate anyone who has the right conversion.

Thanks!

**Comment by ngoossens** [comment]
@thomasck, did you find a solution for the conversion?
