### ISSUE TITLE
Is somethings wrong with Accelerometer Sensitivity

### ISSUE THREAD

**Issue by meekittipol** [jrowberg/i2cdevlib#312]
Accelerometer reading values ( full scale range at +/- 2G ) 
values should be 16384 lsb/g

but values i've read it is 8192 lsb/g

I didn't understand this one, Is somethings wrong

thanks in advance.

**Comment by alexzk1** [comment]
it is half of 16384 = half of 2G = 1G = Earth gravitation.

**Comment by meekittipol** [comment]
Thanks for your reply.

**Comment by meekittipol** [comment]
may be it should read 16384 LSB at 1G 
insane of 8192 LSB at 1G

**Comment by alexzk1** [comment]
...no...total range is 2G:

16k = 2G
8K  = XG
X = 8K *2G /16K = 1G

**Comment by alexzk1** [comment]
scale is dependent on BITNESS of variables, i.e. int16_t will have 16k scale, so depends which u use.

**Comment by meekittipol** [comment]
I get it.

Thanks a lot for your reply @alexzk1
