### ISSUE TITLE
MPU6050_DMP6 PDE serial alignment

### ISSUE THREAD

**Issue by andig** [jrowberg/i2cdevlib#32]
It feels stupid, but I could not get the PDE achieve serial alignment with my Arduino. To fix this I've changed `serialEvent` to reset the `serialCount` whenever the `aligned` was reset to 0 by adding this line right before the print statement:

```
        if(aligned == 0) serialCount = 0; else  serialCount++;            
        println(aligned + " " + serialCount + " " + ch);
```

I don't see how serialCount should otherwise become 0 when $ is received. Not sure if I caused this by some changes to the Arduino example, but this way the alignment really works for me ;)

**Comment by jrowberg** [comment]
Closing ancient issue for cleanup.
