### ISSUE TITLE
MPU6050 OUTPUT_READABLE_WORLDACCEL

### ISSUE THREAD

**Issue by andig** [jrowberg/i2cdevlib#34]
According to code documentation, OUTPUT_READABLE_WORLDACCEL should return "acceleration components with gravity removed". According to http://forum.arduino.cc/index.php?topic=133273 we're constantly seeing ~4000 values around the z-axis which seems to be the gravity value (expected ~0 instead).
Not sure this is a software issue or a misunderstanding what OUTPUT_READABLE_WORLDACCEL is supposed to do?

**Comment by jrowberg** [comment]
Closing ancient issue for cleanup. Fix implemented in `MPU6050_6Axis_MotionApps20.h` some time ago.
