### ISSUE TITLE
MPU6050 - OUTPUT_READABLE_YAWPITCHROLL

### ISSUE THREAD

**Issue by Kolyunya** [jrowberg/i2cdevlib#35]
Hello, Jeff! Thank you for a great library. Your MPU6050 driver is working fine on my Arduino UNO, but I faced some issues in calculating readable yaw-pitch-roll.

I've noticed two problems:
1. Event if the chip was not moved even a tiny bit since the the moment the MPU was initialized, the initial values of yaw-pitch-roll are between `1` and `3`. It seems to me they must all be `0` right after the initialization if the chip was not moved.
2. Even if the chip is absolutely fixed on the steady surface the yaw-pitch-roll values continuously change with deltas about `1` degree  ( e.g. from `3.000` to `3.999`). Is it how the device and the driver are supposed to work or I'm doing something wrong?

Any help or answer is greatly appreciated!

**Comment by mtahak23** [comment]
How can I calculate yaw angle? I am calculating roll and pitch with Kalman filter for my quadrotor. But I don't know to use which quation for that.

**Comment by Rossages** [comment]
Thank you for your libraries Jeff they have been very helpful! :) I am having the same problem with the yaw initially drifting. I have found that it goes stable after approximately 15 seconds.

**Comment by hashimalikhan** [comment]
Hi,
I am using MPU6050 with the DMP6 example. The IMU is working fine except the values do not ever reach 90 deg when the IMU is placed vertical around pitch or roll axis. Instead the values just touch 60deg or sometimes 50deg. Timely response is highly appreciated.
Regards and thanks in advance.
