### ISSUE TITLE
Arduino/i2cdev/I2cDev.h should define BUFFER_LENGTH?

### ISSUE THREAD

**Issue by themarwhal** [jrowberg/i2cdevlib#370]
Am I missing something here? The directory won't compile because i2cdev.cpp relies on a macro called BUFFER_LENGTH being defined. I assumed it should be defined in I2CDev.h so I defined it in there to make it compile. Is this intentional?

**Comment by jrowberg** [comment]
The `BUFFER_LENGTH` constant is defined as `32` in core files for the Arduino Uno and compatible. However, it's not present in all other cores (e.g. ESP32). The I2Cdev library needs to be made more robust across multiple platforms in this regard; an `#ifndef ...` guard with a redefinition should get you by for the moment.

**Comment by MarquisNelsonManova** [comment]
hello
how to download this libary
thanks in advance
