### ISSUE TITLE
how to download and install just  a single lib (Arduino  MPU6050) ?

### ISSUE THREAD

**Issue by dsyleixa** [jrowberg/i2cdevlib#400]
how to download and install just  a single lib (Arduino MPU6050) ?

**Comment by ajuancer** [comment]
I have done it, I attach it [here](https://drive.google.com/open?id=1YKh6de9f3neBtFuB4ZeSCPXde---QrpY). 
You only have to copy the files you want.
Remember to move the folder I attach to Documents/Arduino/Libraries

**Comment by dsyleixa** [comment]
yes, I know how to install the entire i2cdevlib, but I just wanted 1 single lib (MPU6050).
Of course I can copy and paste them from the entire zip file arbitrarily but I asumed there was a simpler way for either single lib.

**Comment by jrowberg** [comment]
This is an unfortunate side-effect of the way this project has grown into a multi-platform beast all under a single monolithic repository. I am working on a significant "reboot" that will be much easier for community development and platform-specific/library-specific integration in modern ecosystems like the Arduino library manager and PlatformIO, etc. But there's no good way to do the same thing with the existing single i2devlib repo without breaking a whole lot of backwards compatibility. :(

**Comment by dsyleixa** [comment]
thanks for your reply! I appreciate very much your efforts on providing all that stuff, I just didn't understand from the start  that all is in the big repo .zip and can be arbitrarily inalled by c+p'ing the single folders.
That's actually not an issue now any more, thanks again!

**Comment by ajuancer** [comment]
I hope it was worth it!!, @dsyleixa 
If you have any questions, feel free to write here.

**Comment by dsyleixa** [comment]
> 
> 
> I hope it was worth it!!, @dsyleixa
> If you have any questions, feel free to write here.

thanks, tbh, there is still a major unresolved issue reported here:
https://github.com/jrowberg/i2cdevlib/issues/399
