### ISSUE TITLE
 MPU6050 lib documentation: is the MPU6050 interrupt pin used or not? 

### ISSUE THREAD

**Issue by dsyleixa** [jrowberg/i2cdevlib#401]
as to the MPU6050 lib documentation:
is the MPU6050 interrupt pin used or not? 
In case yes, to which Arduino pin must it be attached?

**Comment by ajuancer** [comment]
Yes, it's used to control the data that the Arduino receives. 
The pin 2 of the Arduino UNO.

**Comment by dsyleixa** [comment]
where can that be defined and changed in the code?
I have an Adafruit  Feather M4 (and an Itsybitsy M0) and pin2 is not available or already taken.

**Comment by jrowberg** [comment]
It's a `#define` statement in the .ino file:

https://github.com/jrowberg/i2cdevlib/blob/2e9042c82d2b512a060d200dd3f772fe336c57e5/Arduino/MPU6050/examples/MPU6050_DMP6/MPU6050_DMP6.ino#L122

**Comment by dsyleixa** [comment]
I see, thank you very much!
