### ISSUE TITLE
Function for obtaining pitch, roll and yall.

### ISSUE THREAD

**Issue by ajuancer** [jrowberg/i2cdevlib#406]
Is there any function in the library for Arduino that gives you yall, pitch and roll values?
And another function to calibrate the MPU6050?

**Comment by ajuancer** [comment]
@dsyleixa thanks, but that was the code on which I based myself, but it doesn't calibrate the plate when u run the code. I was trying to combine MPU_calibration &  
MPU_DMP6(the code u send me)

**Comment by dsyleixa** [comment]
> 
> 
> @dsyleixa thanks, but that was the code on which I based myself, but it doesn't calibrate the plate when u run the code. I was trying to combine MPU_calibration &
> MPU_DMP6(the code u send me)

it was my answer about your 1st question, i.e.
Is there any function in the library for Arduino that gives you yall, pitch and roll values?
I suppose my reply does answer this 1st question, doesn't it?

As to your 2nd question, I do not have an answer, to this other people may reply.

**Comment by ajuancer** [comment]
@dsyleixa yes, you answer my first question, but when you mix the calibration sketch and the function you mention, I get an error, as you can see in #404
