### ISSUE TITLE
DMP get crazy!!!

### ISSUE THREAD

**Issue by Pluscrafter** [jrowberg/i2cdevlib#414]
My MPU6050 get sometimes crazy after a certain amount of time. I've use my imu with the raspi zero and I've bitbanged the PCA9685 on another pins, because the DMP stucks, when i try to communicate with the PCA9685. Could it be the bintbanging, that the DMP get crazy and outputs faulty values.

**Comment by jrowberg** [comment]
This is almost certainly related to #252. Closing this to avoid splitting the same topic into yet another thread.
