### ISSUE TITLE
What does DMP mean?

### ISSUE THREAD

**Issue by jens1o** [jrowberg/i2cdevlib#442]
Hey there!
Thanks for your project. I wonder what DMP means/stands for, as I couldn't find it anywhere online …
I'd be glad if somebody could point it out for me. :)

Thanks in advance! :)

**Comment by HowardWolosky** [comment]
I believe DMP == [Digital Motion Processor](http://www.geekmomprojects.com/mpu-6050-dmp-data-from-i2cdevlib/)

**Comment by jens1o** [comment]
Ah, this makes sense. Thank you :=)
