### ISSUE TITLE
ISR not in IRAM

### ISSUE THREAD

**Issue by StromRick** [jrowberg/i2cdevlib#443]
Hi, i'm having some trouble on startup: whenever i run the sketch from a nodemcu esp8266 (MPU6050_DMP6_ESPWiFi example) the output tells me "ISR is not in IRAM" just during the attachinterrupt() event. i'm kinda newbish on arduino/esp programming but i'm sure the connection and pin mapping are right and i don't really know why it gets me this error from the vanilla example

**Comment by just-jason** [comment]
I have the same issue

**Comment by StromRick** [comment]
> I have the same issue

i've found a momentary solution, going back a couple of version of the esp in the board manager seems to resolve the problem. I'm currently using 2.5.0 instead of 2.5.2 and works just fine

**Comment by gdsports** [comment]
More [discusson](https://forum.arduino.cc/index.php?topic=616264.msg4182494#msg4182494) about this problem.

Change line 149 to add ICACHE_RAM_ATTR as follows. I will submit a PR with this change.

`void ICACHE_RAM_ATTR dmpDataReady() {
`

**Comment by mviboolr** [comment]
Thank you . for 2.5.0 is works fine.
