### ISSUE TITLE
compiler error

### ISSUE THREAD

**Issue by megarduino** [jrowberg/i2cdevlib#45]
get a very long list of error messages by compiling MPU6000_DMP6.ino.
use Arduino 1.0.5 (tried also 1.5.2, same list), selected board is Mega 2560
I uploaded the i2cdevlib-master today and copied all necessary files in the libraries folder. Do I use an old file or wrong Arduino version?

list starts with 
C:\Program Files\Arduino\libraries\MPU60X0\MPU60X0.cpp: In member function 'void MPU60X0::initialize()':
C:\Program Files\Arduino\libraries\MPU60X0\MPU60X0.cpp:69: error: 'SPI' was not declared in this scope
C:\Program Files\Arduino\libraries\MPU60X0\MPU60X0.cpp: In member function 'uint8_t MPU60X0::getAuxVDDIOLevel()':
C:\Program Files\Arduino\libraries\MPU60X0\MPU60X0.cpp:100: error: invalid conversion from 'int' to 'uint8_t_'
C:\Program Files\Arduino\libraries\MPU60X0\MPU60X0.cpp:100: error:   initializing argument 4 of 'static int8_t I2Cdev::readBit(uint8_t, uint8_t, uint8_t, uint8_t_, uint16_t)'
C:\Program Files\Arduino\libraries\MPU60X0\MPU60X0.cpp:100: error: invalid conversion from 'uint8_t*' to 'uint16_t'
C:\Program Files\Arduino\libraries\MPU60X0\MPU60X0.cpp:100: error:   initializing argument 5 of 'static int8_t

**Comment by jrowberg** [comment]
Closing ancient issue for cleanup.
