### ISSUE TITLE
L3G4200D Gyro outputting strange values

### ISSUE THREAD

**Issue by ghost** [jrowberg/i2cdevlib#46]
I'm using an L3G4200D on a Gy-80 sensor board with an Arduino Due.

The raw values obtained when running the L3G4200D_raw.ino code range from 0 to 255, there is no difference between clockwise and counter clockwise rotations. 

The issue doesn't happen when using the L3G.h library (https://github.com/pololu/L3G) so it doesn't seem to be a hardware issue.

**Comment by jrowberg** [comment]
Closing ancient issue for cleanup.
