### ISSUE TITLE
I can't download this library

### ISSUE THREAD

**Issue by taniapetri** [jrowberg/i2cdevlib#480]
there's no option to download the library. I also created an account but it doesn't work. I'm noob, pleasea help :(

**Comment by Pluscrafter** [comment]
![asdf1](https://user-images.githubusercontent.com/37458188/66604241-0f987f80-ebae-11e9-86af-03dec392c430.PNG)
![asdf2](https://user-images.githubusercontent.com/37458188/66604247-11fad980-ebae-11e9-855d-91cd3d45ba37.PNG)
Hope it's clear enough :)
