### ISSUE TITLE
Warnings at compile time

### ISSUE THREAD

**Issue by jc508** [jrowberg/i2cdevlib#484]
Hi,
Compiling in the Arduino IDE yields over 1000 lines of warnings.
Apart from being 'noise' it looks like some are generated by multiple definitions of objects.
Am I unusual or does everybody see these ??
[MPU6050_DMP6_compiler_warnings.txt](https://github.com/jrowberg/i2cdevlib/files/3746361/MPU6050_DMP6_compiler_warnings.txt)

**Comment by diyargur** [comment]
i also get the same error message!

**Comment by diyargur** [comment]
Hi,
The sketch compiles cleanly in the Arduino IDE 1.8.9 using 1.6.21 board manager version.

**Comment by Tanishqwayne** [comment]
hey, I have the same problem .when I compile the code, it says it's compiled but leaves so many lines of warnings and the output is affected.

**Comment by jrowberg** [comment]
This is a known issue which will hopefully (finally) be fixed in the next week or so. It comes from a poor architectural decision very early in the life of the MPU6050 code. There are multiple issues addressing this, so I’m closing most of them now.
