### ISSUE TITLE
Cant get rid of annoying message of Jeff's library

### ISSUE THREAD

**Issue by batata004** [jrowberg/i2cdevlib#565]
The print simple code below everytime I run it, shows the message down further:

```
#include "MPU6050_6Axis_MotionApps20.h"
MPU6050 mpu;

void setup() {
  
  Serial.begin(115200);
  
  Wire.begin();
  Wire.setClock(400000);
  mpu.initialize();
  
  mpu.dmpInitialize();

}

void loop() {

}
```

Message:

```
Checking hardware revision...
Revision @ user[16][6] = A5
Resetting memory bank selection to 0...

```

I am not using "#define DEBUG" and nothing like that. My `MPU6050_6Axis_MotionApps20.h` file is exactly as the same in this repository, however everytime I run that simple code, it displays those unnecessary message. How do I make my arduino not display those messages?

**Comment by jrowberg** [comment]
Fixed with https://github.com/jrowberg/i2cdevlib/commit/10bcf2b49f82feec316871ac360a7e0be25b45f8
