### ISSUE TITLE
Compiler Error uint8_t Trash[BUFFER_LENGTH] not declared

### ISSUE THREAD

**Issue by volkerpetersen** [jrowberg/i2cdevlib#570]
when I compile my program using the library function mpu.dmpGetCurrentFIFOPacket(fifoBuffer) I get the compiler errors:
E:\VolkerPetersen\Dropbox\ProgramCode\MicroProcessorProjects\libraries\MPU6050\src\MPU6050.cpp:2763:32: error: 'BUFFER_LENGTH' was not declared in this scope
                  uint8_t Trash[BUFFER_LENGTH];

and
E:\VolkerPetersen\Dropbox\ProgramCode\MicroProcessorProjects\libraries\MPU6050\src\MPU6050.cpp:2769:39: error: 'Trash' was not declared in this scope
                          getFIFOBytes(Trash, (uint8_t)RemoveBytes);

Any suggestions?

**Comment by ZHomeSlice** [comment]
#define BUFFER_LENGTH 32 // I'm assuming your processors i2c buffer is 32 bytes in length

you need this before you include your libraries

Z

**Comment by volkerpetersen** [comment]
Thx!

 

Volker

507-837-9868

**Comment by bill-richards** [comment]
> #define BUFFER_LENGTH 32 // I'm assuming your processors i2c buffer is 32 bytes in length
> 
> you need this before you include your libraries
> 
> Z

Where is this documented please?

**Comment by jrowberg** [comment]
Errors related to undefined `BUFFER_LENGTH` have now been resolved.
