### ISSUE TITLE
Why it is incompatible with arduino uno r3? and when I tried it with esp32 it is giving me error buffer length is not defined in this scope

### ISSUE THREAD

**Issue by Shikhar0708** [jrowberg/i2cdevlib#574]

**Comment by Shikhar0708** [comment]
why is it incompatible with arduino unpo r3?

**Comment by ZHomeSlice** [comment]
UNO uses 
#define BUFFER_LENGTH 32
esp32 **may** have the same i2c buffer length but the Arduino ide doesn't define this for you you have to.
add the #define line before your includes and it should work.

**Comment by Shikhar0708** [comment]
Okay and can you please help me with why i cant compile it for arduino uno

**Comment by nices0325** [comment]
> 좋아, 왜 내가 arduino uno를 위해 컴파일 할 수 없는지 도와 주시겠습니까?

all most all of the atmega328 chip included arduino worked well..  redownload and refesh all the files and rerun it

**Comment by Shikhar0708** [comment]
would you please have a look at my code?
#include "IMU.h"

#define NUM_SAMPLES 30
#define NUM_AXES 3
// sometimes you may get "spikes" in the readings
// set a sensible value to truncate too large values
#define TRUNCATE_AT 20

double features[NUM_SAMPLES * NUM_AXES];

void setup() {
    Serial.begin(115200);
    imu_setup();
}

void loop() {
    float ax, ay, az;

    imu_read(&ax, &ay, &az);

    ax = constrain(ax, -TRUNCATE_AT, TRUNCATE_AT);
    ay = constrain(ay, -TRUNCATE_AT, TRUNCATE_AT);
    az = constrain(az, -TRUNCATE_AT, TRUNCATE_AT);

    Serial.print(ax);
    Serial.print('\t');
    Serial.print(ay);
    Serial.print('\t');
    Serial.println(az);
}

**Comment by jrowberg** [comment]
Errors related to undefined `BUFFER_LENGTH` have now been resolved with an addition to `I2Cdev.h` detecting and/or defining a suitable length for many platforms.
