### ISSUE TITLE
How to Stop MPU6050 DMP? 

### ISSUE THREAD

**Issue by williamesp2015** [jrowberg/i2cdevlib#590]
In my program I have to start and stop reading MPU6050 and I am using MPU6050_6Axis_MotionApps_V6_12. I couldn't find an reliable function to stop and restart DMP.

**Comment by flavioipiranga** [comment]
Hi @williamesp2015,

Check if this helps: https://github.com/jrowberg/i2cdevlib/blob/474c5e4fd2bbf3a486f40a79b7c908d0f49d3ab5/Arduino/MPU6050/MPU6050.cpp#L3022
