### ISSUE TITLE
MPU-6050 & tiva C launch pad tm4c123

### ISSUE THREAD

**Issue by mahmoudhamdy** [jrowberg/i2cdevlib#62]
i tried to use the library on energia and everything worked fine but when i print the raw values they arenot stable at all it goes up and down strangely with no reason and with no movement however it works fine on arduino ! ..

anyone can help ?

**Comment by Hrishikeshkunchepu** [comment]
Hi, mahmoudhamdy, did you get the output correctly?

**Comment by jrowberg** [comment]
Closing ancient issue for cleanup.
