### ISSUE TITLE
world-based yaw?

### ISSUE THREAD

**Issue by mark-hahn** [jrowberg/i2cdevlib#641]
I have a tilted 6050 chip in my bot but I need the yaw value referenced around the gravity vector.  In other words I need a world-based yaw.  I see world-based acceleration but nothing world-based for ypr.  Am I missing something simple?   I assume it would be some math on the quaternion.

Actually I would be happy with a fixed rotation on just one axis since my sensor is fixed in my bot and is only rotated on one axis.  I noticed the orientation stuff for the dmp but it seems to be fixed to 90 degree rotations, in other words flipping the axes around.  I need a 60 degree rotation.

This is a bit of a duplicate of https://github.com/jrowberg/i2cdevlib/issues/637 but I've figured out this simpler shorter way of asking.

**Comment by jrowberg** [comment]
World-based yaw requires a magnetometer, which allows full 9-DOF sensor fusion. Gravity provides world reference for the accelerometer anywhere on the planet, and the gyro is entirely relative anyway, but the only way to establish a common heading reference is with a compass. Without that, you have to pick an arbitrary heading value as your virtual north/zero starting point.
