### ISSUE TITLE
msp430_i2c.c: cannot open source file "i2c.h"

### ISSUE THREAD

**Issue by xumengmeng** [jrowberg/i2cdevlib#74]
Hi,
I download the lib for MP430,
when I compile it, there is an error as following:

Description Resource    Path    Location    Type
#1965 cannot open source file "i2c.h"   msp430_i2c.c    /MPU9150    line 14 C/C++ Problem

Line 14: #include "i2c.h"

did I do something wrong? i cannot find the file anywhere.
sorry, I am quite new in this.

Thanks.

**Comment by sunilshahu** [comment]
Hi,

Is there any solution for this error? 

Here is the list of files in my CCS project.

ArduinoWrapper.h
I2Cdev.h
MPU6050_6Axis_MotionApps20.h
MPU6050_9Axis_MotionApps41.h
MPU6050.h
msp430_i2c.h
I2Cdev.cpp
MPU6050.cpp
msp430_i2c.c
main.c

**Comment by nokiann** [comment]
To get the MPU6050 to work with the MSP430G2553 go with this:
https://github.com/energia/Energia/issues/486
and try the default Arduino example:
http://playground.arduino.cc/Main/MPU-6050#short
Watch out for the I2C pin mapping! You have to add "Wire.setModule(0);" before "Wire.begin()" to use the default SDA/SCL pins!

**Comment by jrowberg** [comment]
Closing ancient issue for cleanup.
