### ISSUE TITLE
is OUTPUT_READABLE_YAWPITCHROLL display Euler angles in degrees conversion correct?

### ISSUE THREAD

**Issue by mw66** [jrowberg/i2cdevlib#763]
https://github.com/jrowberg/i2cdevlib/blob/605a7401b05baebef146dc5caa3d0e8e15841e49/Arduino/MPU6050/examples/MPU6050_DMP6/MPU6050_DMP6.ino#L294

Is this conversion correct?

Why when I put my chip vertical (90 degree), the print output is: 28.07, i.e. (~= 90 / 3.14 = 28.66)?

BTW, I got ~+/- 0.xx at zero degrees.

what I'm missing?

Thanks.

**Comment by jrowberg** [comment]
Closing with comment and possible continuing discussion left on https://github.com/ElectronicCats/mpu6050/issues/74.
