### ISSUE TITLE
return status missing

### ISSUE THREAD

**Issue by aspineux** [jrowberg/i2cdevlib#8]
Their is no way to know if a function was successful or not !
For example, when using 
void MPU6050::getMotion6(int16_t\* ax, int16_t\* ay, int16_t\* az, int16_t\* gx, int16_t\* gy, int16_t\* gz);

I don't know if the value in a? and g? are valid or not.

The function could return a boolean and/or set an error flag for function that already return a value. 

This is useful to detect  a disconnect wire when working with a breadboard.

This concern at least MPU6050 and DS1307 and probably all the other classes
I think the easiest way would be to inherit from I2Cdev and setup and error flag after a failed read or write.

Thanks for your work
Alain

**Comment by jrowberg** [comment]
Closing ancient issue for cleanup.
