### ISSUE TITLE
MPU6050_6Axis_MotionApps20.h - where is 0x01 on line 261?

### ISSUE THREAD

**Issue by ILANE1** [jrowberg/i2cdevlib#85]
Hi!
Coding-wise, I am not there yet, but I've read about "change the output rate of the DMP to something slower than 100Hz, by modifying the last byte on line 261.....The default value is 0x01, but setting it to 0x07 will give you a 25Hz rate". Looking at the file dated 5/20/2013, and fail repeatedly to locate any 0x01 in the vicinity.
Perhaps you could point to the significant byte by specifying bank # (is it in bank 7?) and its ordinal number in said bank. Or let me know what is it that am I totally misunderstanding about this.
Many thanks.
As a side bonus, perhaps you can point to a good place to read about optimizing the output rate of the DMP to my application (yet another home brewed Segway clone, done by sexagenarians).

**Comment by jrowberg** [comment]
Closing ancient issue for cleanup.
