### ISSUE TITLE
MPU6050 connected to UNO,FIFO overflow

### ISSUE THREAD

**Issue by xuxubin** [jrowberg/i2cdevlib#87]
Hi!
I connected the MPU6050 to the Arduino UNO(the connection is correct) and used the library:
https://github.com/jrowberg/i2cdevlib/tree/master/Arduino/MPU6050
I burned the demo MPU6050_DMP6.ino and it can read out the data.
However it always said the FIFO overflow.
If the demo is ok, is there anything I may did wrong?
Thank for your help.

**Comment by kplrm** [comment]
hi! I got the same problem. Im trying to send the data wireless (via Bluetooth) and disabling the wired connection. I'm using the <SoftwareSerial.h> lib and an arduino micro/leonardo.

The data is sent correctly (Baud 115200) but after a while it stops. Almost at the beginning it appears this FIFO overflow message. Could be this FIFO overflow the reason?

**Comment by jrowberg** [comment]
Closing ancient issue for cleanup.
