### ISSUE TITLE
MPU6050_raw compile errors

### ISSUE THREAD

**Issue by linnealovespie** [jrowberg/i2cdevlib#88]
First off, this library is a lifesaver! I'm brand new to Arduino and using the MPU-6050, and have yet to learn a lot about how this all works. I've cloned the code, added the header files to the right directory, opened the MPU6050_raw program and compiled to receive a bunch of ugly errors:

MPU6050.cpp.o: In function `MPU6050::getMotion6(int*, int*, int*, int*, int*, int*)':
C:\Users\Linnea\AppData\Local\Temp\build554160420100942289.tmp/MPU6050.cpp:1735: undefined reference to`I2Cdev::readTimeout'
C:\Users\Linnea\AppData\Local\Temp\build554160420100942289.tmp/MPU6050.cpp:1735: undefined reference to `I2Cdev::readTimeout'
C:\Users\Linnea\AppData\Local\Temp\build554160420100942289.tmp/MPU6050.cpp:1735: undefined reference to`I2Cdev::readBytes(unsigned char, unsigned char, unsigned char, unsigned char_, unsigned int)'
MPU6050.cpp.o: In function `MPU6050::setSleepEnabled(bool)':
C:\Users\Linnea\AppData\Local\Temp\build554160420100942289.tmp/MPU6050.cpp:2384: undefined reference to`I2Cdev::writeBit(unsigned char, unsigned char, unsigned char, unsigned char)'
MPU6050.cpp.o: In function `MPU6050::setClockSource(unsigned char)':
C:\Users\Linnea\AppData\Local\Temp\build554160420100942289.tmp/MPU6050.cpp:2477: undefined reference to`I2Cdev::writeBits(unsigned char, unsigned char, unsigned char, unsigned char, unsigned char)'
MPU6050.cpp.o: In function `MPU6050::setFullScaleAccelRange(unsigned char)':
C:\Users\Linnea\AppData\Local\Temp\build554160420100942289.tmp/MPU6050.cpp:329: undefined reference to`I2Cdev::writeBits(unsigned char, unsigned char, unsigned char, unsigned char, unsigned char)'
MPU6050.cpp.o: In function `MPU6050::setFullScaleGyroRange(unsigned char)':
C:\Users\Linnea\AppData\Local\Temp\build554160420100942289.tmp/MPU6050.cpp:253: undefined reference to`I2Cdev::writeBits(unsigned char, unsigned char, unsigned char, unsigned char, unsigned char)'
MPU6050.cpp.o: In function `MPU6050::getDeviceID()':
C:\Users\Linnea\AppData\Local\Temp\build554160420100942289.tmp/MPU6050.cpp:2698: undefined reference to`I2Cdev::readTimeout'
C:\Users\Linnea\AppData\Local\Temp\build554160420100942289.tmp/MPU6050.cpp:2698: undefined reference to `I2Cdev::readTimeout'
C:\Users\Linnea\AppData\Local\Temp\build554160420100942289.tmp/MPU6050.cpp:2698: undefined reference to`I2Cdev::readBits(unsigned char, unsigned char, unsigned char, unsigned char, unsigned char_, unsigned int)'

Some help for this poor ignorant soul would be greatly appreciated.

**Comment by kasunm2ak** [comment]
Get i2cdevlib from this linkhttp://github.com/jrowberg/i2cdevlib or just  git clone if your linux user.
then go to i2cdevlib--> arduino folder.There have a folder name with I2Cdev ,just copy that folder in to your library folder in your workspace and then restart the IDE .It will compile now
