### ISSUE TITLE
Hard coded I2C address for MPU6050 in MotionApps

### ISSUE THREAD

**Issue by tsimon57** [jrowberg/i2cdevlib#91]
There is a variable for the I2C device address in MPU6050.cpp, but in both of the includes files for MotionApps there are hard coded calls to I2Cdev member functions using hard coded values ("0x68") for the device address.  I can update this but wanted to check to see if there was a reason for this first. Look at MotionApps 41 on lines 474 to 507.

Thanks!

**Comment by jrowberg** [comment]
Closing ancient issue for cleanup.
