### ISSUE TITLE
What is the sample rate of MPU6050_DMP?

### ISSUE THREAD

**Issue by 54272115** [jrowberg/i2cdevlib#93]
I want to plot a graph from the values I get.
1. The values that I get are in degrees, right?
2. Where can I find the sample rate?

Thank you in advance

**Comment by findftp** [comment]
Go to MPU6050_6Axis_MotionApps20.h and look for the lines: 
    0x02,   0x16,   0x02,   0x00, 0x01                // D_0_22 inv_set_fifo_rate

    // This very last 0x01 WAS a 0x09, which drops the FIFO rate down to 20 Hz. 0x07 is 25 Hz,
    // 0x01 is 100Hz. Going faster than 100Hz (0x00=200Hz) tends to result in very noisy data.
    // DMP output frequency is calculated easily using this equation: (200Hz / (1 + value))

    // It is important to make sure the host processor can keep up with reading and processing
    // the FIFO output at the desired rate. Handling FIFO overflow cleanly is also a good idea.

It should explain your qeustion.

**Comment by Holei** [comment]
Thank you very much!
Horst Leistner
  ----- Original Message -----

**Comment by jrowberg** [comment]
Closing ancient issue for cleanup.
