### ISSUE TITLE
Accelerometer LSB Sensitivity

### ISSUE THREAD

**Issue by gioalex** [jrowberg/i2cdevlib#94]
Hi,

reading MPU6050 datasheet I've noticed that there is a difference in LSB Sensitivity from what you have written in your code.

You wrote (both in code && documentation):

AFS_SEL | Full Scale Range | LSB Sensitivity
 --------+------------------+----------------
 0       | +/- 2g           | 8192 LSB/mg
 1       | +/- 4g           | 4096 LSB/mg
 2       | +/- 8g           | 2048 LSB/mg
 3       | +/- 16g          | 1024 LSB/mg

Datasheet say:

AFS_SEL | Full Scale Range | LSB Sensitivity
 --------+------------------+----------------
 0       | +/- 2g           | 16384 LSB/mg
 1       | +/- 4g           | 8192 LSB/mg
 2       | +/- 8g           | 4096 LSB/mg
 3       | +/- 16g          | 2048 LSB/mg

maybe an error?

Regards.
Alessandro.

**Comment by serenalsx** [comment]
I agree. And I think the 0 | +/- 2g | 8192 LSB/mg in code&&documentation is wrong.

**Comment by jrowberg** [comment]
Closing ancient issue for cleanup. Corrected in comments moments ago.
