### ISSUE TITLE
Two MPU6050, one Arduino

### ISSUE THREAD

**Issue by HealFheonix** [jrowberg/i2cdevlib#98]
As titled, is this possible? I have attempted to modify Jeff's original code (defining "Yaw Pitch Roll") for hours but to no avail.

My only successful attempt resulted in the data causing an "FIFO Overflow!" error every 1 second, before ending the data collection some 10-15 seconds later. 

Anything would be fantastic. Ive seen other examples of dual MPU6050 but they have not been able to produce YPR quite like Jeffs, which i really need for my project. Thanks!

**Comment by conde1990** [comment]
hey 
i need a code to implemente kaplan filter in MPU6050. i need your help

**Comment by jrowberg** [comment]
Closing ancient issue for cleanup.
